const actionTypes = Object.freeze({
  //APP
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  // MENU
  SET_MENU: "SET_MENU",

  // LOADING
  LOADING_TOGGLE_ACTION: "LOADING_TOGGLE_ACTION",
  // CLEAR STATUS
  CLEAR_STATUS: "CLEAR_STATUS",

  // ADMIN

  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAILED: "CREATE_FAILED",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILED: "DELETE_FAILED",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILED: "UPDATE_FAILED",

  // FILE
  GET_LIST_FILE_SUCCEED: "GET_LIST_FILE_SUCCEED",
  GET_LIST_FILE_FAILED: "GET_LIST_FILE_FAILED",
  GET_LIST_FILE_HOME_SUCCEED: "GET_LIST_FILE_HOME_SUCCEED",
  GET_LIST_FILE_HOME_FAILED: "GET_LIST_FILE_HOME_FAILED",
  CREATE_FILE_SUCCEED: "CREATE_FILE_SUCCEED",
  CREATE_FILE_FAILED: "CREATE_FILE_FAILED",
  GET_FILE_SUCCEED: "GET_FILE_SUCCEED",
  GET_FILE_FAILED: "GET_FILE_FAILED",
});

export default actionTypes;
