const actionTypes = Object.freeze({
  //APP
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  // MENU
  SET_MENU: "SET_MENU",

  // LOADING
  LOADING_TOGGLE_ACTION: "LOADING_TOGGLE_ACTION",
  // CLEAR STATUS
  CLEAR_STATUS: "CLEAR_STATUS",

  // ADMIN

  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAILED: "CREATE_FAILED",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILED: "DELETE_FAILED",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILED: "UPDATE_FAILED",

  // CLINIC
  GET_LIST_CLINIC_SUCCEED: "GET_LIST_CLINIC_SUCCEED",
  GET_LIST_CLINIC_FAILED: "GET_LIST_CLINIC_FAILED",
  GET_LIST_CLINIC_HOME_SUCCEED: "GET_LIST_CLINIC_HOME_SUCCEED",
  GET_LIST_CLINIC_HOME_FAILED: "GET_LIST_CLINIC_HOME_FAILED",
  CREATE_CLINIC_SUCCEED: "CREATE_CLINIC_SUCCEED",
  CREATE_CLINIC_FAILED: "CREATE_CLINIC_FAILED",
  GET_CLINIC_SUCCEED: "GET_CLINIC_SUCCEED",
  GET_CLINIC_FAILED: "GET_CLINIC_FAILED",
  PATIENT_GET_LIST_CLINIC_SUCCEED: "PATIENT_GET_LIST_CLINIC_SUCCEED",
  PATIENT_GET_LIST_CLINIC_FAILED: "PATIENT_GET_LIST_CLINIC_FAILED",
  PATIENT_GET_CLINIC_SUCCEED: "PATIENT_GET_CLINIC_SUCCEED",
  PATIENT_GET_CLINIC_FAILED: "PATIENT_GET_CLINIC_FAILED",
});

export default actionTypes;
